### PR TITLE
docs: define component states

### PR DESCRIPTION
**Pull request by larsrickert**
Define/document available component states.

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [x] All changes are documented in the documentation app (folder `apps/docs`)
- [x] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [x] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

### CODE REVIEW

**Comment by JoCa96** [comment]
I believe this information might be better suited for our wiki or maybe UX docs. Its geared towards developers and UX.

**Comment by larsrickert** [comment]
> I believe this information might be better suited for our wiki or maybe UX docs. Its geared towards developers and UX.

It is already placed inside the UX docs :) Jannick already created a UX page for the component states. This PR just fills it with content accordingly.

But I can also move it to the Wiki and delete the UX page for component states

**Comment by JoCa96** [comment]
@larsrickert Nice, got it 👍 Then @jannick-ux should do the review please

**Review by JoCa96 — CHANGES_REQUESTED** [review]
Are these states already approved with @jannick-ux? Because I don't think we will group some of them together, e.g. the all kind of error states

**Review by jannick-ux — APPROVED** [review]
Looks fine to me!

**Review by JoCa96 — APPROVED** [review]

**Pull request merged**
